### ISSUE TITLE
Unable to load objects of abstract type from JSON

### ISSUE THREAD

**Issue by JeremyKwok** [AY1920S1-CS2113-T14-1/main#242]
The trivial solution is to store the entire data as a hash map, reconstruct ourselves, will need to create a function to call the constructor of each object and a function to determine the object. 

Alternatively, jacob has started working on a more elegant solution.

**Comment by aquohn** [comment]
I'm confused, what objects of abstract type are you referring to? Are you referring to things like the evidence and treatment maps?

**Comment by JeremyKwok** [comment]
yeah
