### ISSUE TITLE
Junit tests fail for RecurringTasks

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#26]
As @aquohn has already noted in ```NewRecurringTaskCommandTest``` class, dates generated were 1 day off for some reason.

P.S. nice meme at ```NewRecurringTaskCommand``` class :wink:

**Comment by gowgos5** [comment]
Screenshot attached.

![snip](https://user-images.githubusercontent.com/9738454/65394082-be217f80-ddbb-11e9-86f3-fa9acfdbf3c2.PNG)

**Comment by aquohn** [comment]
Fixed in db69b7aa343c4066fcb883220ab0f019c5581371.
