### ISSUE TITLE
As a house officer who has to manage a lot of information, I can search through all of the records of a patient so that I can find all the details relevant to a particular aspect of his/her care plan.

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#33]
```Role```: House officer
```Function```: Search through all of the records of a particular patient
```Benefit```: Find all the details relevant to a particular aspect of his/her care plan

**Comment by aquohn** [comment]
Data retrieval procedure of intermediate utility, not very complex but not extremely useful. Should be easily doable if we have time, but not critical. See #48 for details.
