### ISSUE TITLE
As a house officer who has to manage a lot of information, I can easily view and navigate through data associated with particular conditions that particular patients have, so that I can have a clearer view of what that particular condition is.

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#35]
```Role```: House officer
```Function```: Easily view and navigate through data associated with particular conditions that particular patients have
```Benefit```: Can have a clearer view of what that particular condition is

**Comment by aquohn** [comment]
Somewhat complex GUI interaction, but would be very helpful in tandem with other systems that involve jumping directly to an object without passing through the Impression first. See #48 for details.
