### ISSUE TITLE
As a house officer who needs to upload records into the hospital’s health system, I can generate unified reports that are fully compatible with the system so that I don't have to manually input those records.

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#44]
```Role```: House officer
```Function```: Generate unified reports that are fully compatible with the hospital’s health system
```Benefit```: Don't have to manually input those records

**Comment by aquohn** [comment]
Simple to do, but essential for our product to be useful - the data needs to be able to leave the system. We may not know the output format, but we can use a simple generic text file first and extend in v2.0.
