### ISSUE TITLE
As a house officer keeping track of information for my consultant, I can keep track of whether or not I’ve checked for the results of certain investigations so that I can make sure the consultant is kept up-to-date.

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#45]
```Role```: House officer
```Function```: Keep track of whether or not I’ve checked for the results of certain investigations
```Benefit```: Can make sure the consultant is kept up-to-date

**Comment by aquohn** [comment]
Basic information retrieval and updating.
