### ISSUE TITLE
Developer Guide

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#54]
Should have the user profile, value proposition, and an appendix containing user stories, use cases and NFR.

**Comment by aquohn** [comment]
Guys, I don't think I can do up the whole developer guide, especially the use cases. The user guide I'm working on is kind of like a hybrid user guide and command specification. When I'm done with it, could you guys help disentangle the two and use them to fill out the developer guide? I can do the target user profile and value proposition though!

**Comment by gowgos5** [comment]
@aquohn Hey hey! Don't worry haha. I am not expecting you to do everything yourself. I am just assigning this to you because it falls under your scope. I am looking through the user guide now.
