### ISSUE TITLE
Command "done 0" will result in a program crash

### ISSUE THREAD

**Issue by gowgos5** [AY1920S1-CS2113-T14-1/main#7]
Upper bound is restricted properly. However, do check lower bound as well.

**Comment by aquohn** [comment]
The check is in `getTaskIdx()` in the TaskList class, can you fix and push? The feature I'm working on isn't ready to be pushed yet.

**Comment by gowgos5** [comment]
Roger. WIll do so after I am done with my current extension.

**Comment by gowgos5** [comment]
Resolved (see commit 8541bb8)
